Mise à jour importante du SGB
profcfuhrmanets/log210-systeme-gestion-bordereau-node-express-ts pull request #17
Opened 2024-05-31 10:31 UTC by Olon11

2024-05-31 10:31 UTC, Olon11 commented
Fixes #2

2024-06-10 12:55 UTC, Olon11 commented
Fix #6

2024-06-10 13:10 UTC, Olon11 commented
Fix #3

2024-06-10 13:20 UTC, Olon11 commented
@fuhrmanator Je pense que c'est bien de faire un premier merge, même s'il reste des issues. Au moins, ça facilitera le travail des étudiants.

J'avais inséré tes changements dans ma branche, mais on dirait qu'il reste des conflits. Je peux m'en charger si tu approuves les changements.

2024-06-10 15:56 UTC, fuhrmanator requested changes

2024-06-10 15:56 UTC, fuhrmanator commented on .github/workflows/build-and-tests.yml
> +      - name: Upload coverage data to Coveralls
Veut-on que coveralls soit fait pour chaque OS? C'est un peu overkill. Ça plante le CI en plus (jobs simultanés?). Je pense qu'il faut faire ça dehors de la matrice, dcomme circular-dependencies

2024-06-10 15:56 UTC, fuhrmanator commented on .github/workflows/build-and-tests.yml
> +      - name: Upload coverage data to Coveralls
Je pense qu'une couverture générée par jest sera adéquate -- pas besoin de se vanter -- on dépend aussi d'un système de plus (travis) et un jour ça peut devenir payant/disparaitre.

2024-06-10 16:09 UTC, Olon11 commented on .github/workflows/build-and-tests.yml
> +      - name: Upload coverage data to Coveralls
La couverture est générée par Jest. Elle est seulement transférée à Coveralls pour archivage. Le but n'est pas de se vanter, mais de voir si on régresse. Je ne vois pas comment on dépend de Travis, tout est fait avec Github Actions.

Je vais regarder pour le faire une fois par système d'exploitation.

2024-06-10 16:17 UTC, Olon11 commented on .github/workflows/build-and-tests.yml
> +      - name: Upload coverage data to Coveralls
C'est réglé.

2024-06-10 16:19 UTC, fuhrmanator commented on .github/workflows/build-and-tests.yml
> +      - name: Upload coverage data to Coveralls
Désolé, j'ai confondu coveralls.io et travis, mais mon point est le même (on dépend d'un système tiers). 

Si tu actives la couverture dans jest, elle va rouler dans npm test et les résultats seront dans le log du CI (tu pourras l'avoir pour les 3 OS sans problème). C'est moins visible (pourquoi j'ai dit "se vanter").

2024-06-10 16:26 UTC, fuhrmanator commented
Concernant https://coveralls.io/builds/67993653/source?filename=src%2FApp.ts#L43 -- j'ai fait `it.skip` dans le test qui devait valider cela: https://github.com/profcfuhrmanets/log210-systeme-gestion-bordereau-node-express-ts/blob/1b0aaeb633ed80f14cc33a95c6eb2bd7a36eb883/tests/router/AppRouter.test.ts#L7

2024-06-10 16:27 UTC, fuhrmanator approved these changes

2024-06-10 16:31 UTC, merged